# Site
name: "Mr AndroidDev"
title: "Mr AndroidDev"
description: "Mr AndroidDev."
logo: 'assets/images/favicon.png'
email: contact@mrandroiddev.com
medium: https://medium.com/@s.vinouze
twitter: https://twitter.com/mrandroiddev
linkedin: https://www.linkedin.com/in/stephenvinouze/
github: https://github.com/Mr-AndroidDev
favicon: 'assets/images/favicon.png'
baseurl:
google_analytics: 'UA-166933112-1'
disqus: 'stephenvinouze'
mailchimp-list: 'https://stephenvinouze.us18.list-manage.com/subscribe?u=f1f3eb2d7ae0213227f09dd2c&id=1f16cf654c'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  stephen:
    name: Manohar Reddy
    display_name: Manohar Reddy
    avatar: 'assets/images/avatar.png'
    email: manohar@mrandroiddev.com
    web: https://manoharreddy.ml/
    twitter: https://twitter.com/manohar_reddy_a

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
